import { defineConfig } from 'orval';

export default defineConfig({
	signoz: {
		input: {
			target: '../docs/api/openapi.yml',
			// Perses' `common.JSONRef` (used by `DashboardGridItem.content`) has a
			// field tagged `json:"$ref"`, so our spec contains a property literally
			// named `$ref`.
			// Orval v8's validator (`@scalar/openapi-parser`) treats every `$ref` key
			// as a JSON Reference and aborts with `INVALID_REFERENCE` when the value isn't a URI string.
			// Safe to disable: yes, the spec is generated by `cmd/openapi.go` and gated by backend CI, not hand-edited.
			unsafeDisableValidation: true,
		},
		output: {
			// Preserve the schema import path when the OpenAPI product title changes.
			target: './src/api/generated/services/sigNoz.ts',
			client: 'react-query',
			httpClient: 'axios',
			mode: 'tags-split',
			headers: true,
			clean: true,
			override: {
				query: {
					useQuery: true,
					useMutation: true,
					useInvalidate: true,
					signal: true,
					useOperationIdAsQueryKey: false,
				},
				useDates: false,
				useNamedParameters: true,
				enumGenerationType: 'enum',
				mutator: {
					path: './src/api/generatedAPIInstance.ts',
					name: 'GeneratedAPIInstance',
				},

				jsDoc: {
					filter: (schema) => {
						const allowlist = [
							'type',
							'format',
							'maxLength',
							'minLength',
							'description',
							'minimum',
							'maximum',
							'exclusiveMinimum',
							'exclusiveMaximum',
							'pattern',
							'nullable',
							'enum',
						];
						return Object.entries(schema || {})
							.filter(([key]) => allowlist.includes(key))
							.map(([key, value]) => ({
								key,
								value: String(value),
							}))
							.sort((a, b) => a.key.length - b.key.length);
					},
				},

				components: {
					schemas: {
						suffix: 'DTO',
					},
					responses: {
						suffix: 'Response',
					},
					parameters: {
						suffix: 'Params',
					},
					requestBodies: {
						suffix: 'Body',
					},
				},

				header: (info): string[] => [
					`! Do not edit manually`,
					`* The file has been auto-generated using Orval for Argus`,
					`* regenerate with 'pnpm generate:api'`,
					...(info.title ? [info.title] : []),
					...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
				],

				aliasCombinedTypes: true,
			},
		},
	},
});
