name: build-community

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

defaults:
  run:
    shell: bash

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.7"
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: ghcr-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-and-push
        run: make docker-buildx-community
        env:
          VERSION: ${{ github.ref_name }}
          DOCKER_REGISTRY_COMMUNITY: ghcr.io/${{ github.repository_owner }}/argus
