name: jsci

on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  tsc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec tsgo --noEmit
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - run: pnpm install --frozen-lockfile
      - run: pnpm test -- --ci --watchAll=false
  fmt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - run: pnpm install --frozen-lockfile
      - run: pnpm fmt
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint:js --quiet
  openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - run: cd frontend && pnpm install --frozen-lockfile
      - name: generate-api-clients
        run: |
          cd frontend && pnpm generate:api
          git diff --compact-summary --exit-code || (echo; echo "Unexpected difference in generated api clients. Run pnpm generate:api in frontend/ locally and commit."; exit 1)
  web-settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - run: cd frontend && pnpm install --frozen-lockfile
      - name: generate-web-settings
        run: |
          cd frontend && pnpm generate:config:web-settings
          git diff --compact-summary --exit-code || (echo; echo "Unexpected difference in generated web settings types. Run pnpm generate:config:web-settings in frontend/ locally and commit."; exit 1)
